<?php

/**
 * @file
 * Module file of the translation management OHT module.
 *
 * http://onehourtranslation.com/
 *
 * Implemented by Artem Berdishev, AMgrade
 */

/**
 * Implements hook_tmgmt_translator_plugin_info().
 */
function tmgmt_oht_tmgmt_translator_plugin_info() {
  return array(
    'oht' => array(
      'label' => t('OHT translator'),
      'description' => t('A OneHourTranslation translator service.'),
      'plugin controller class' => 'TMGMTOhtPluginController',
      'ui controller class' => 'TMGMTOhtTranslatorUIController',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function tmgmt_oht_menu() {
  return array(
    'tmgmt_oht_callback' => array(
      'title' => 'TMGMT OHT Callback',
      'description' => '',
      'page callback' => 'tmgmt_oht_callback',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
    'tmgmt_oht_text' => array(
      'title' => 'TMGMT OHT Callback',
      'description' => '',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('tmgmt_oht_post_response'),
      'access callback' => TRUE,
    ),
  );
}

/**
 * Callback for OHT requests.
 */
function tmgmt_oht_callback() {
//  $data = json_decode($_POST['job']);

watchdog('tmgmt_oht', 'receive data => <pre>@data</pre>', array('@data' => print_r($_POST, 1)));
//  $job = tmgmt_job_load($tjid);
//  $oht = $job->getTranslator()->getController();
//  $oht->receiveTranslation($job, $data);
  exit('');
}

function tmgmt_oht_post_response() {
  $form = array();
  $form['params'] = array(
    '#type' => 'textarea',
    '#title' => t('Parameters'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

function tmgmt_oht_post_response_submit($form, &$form_state) {
  $params = $form_state['values']['params'];
  $options = array(
    'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
    'method' => 'POST',
    'data' => $params,
  );
  $response = drupal_http_request(url('tmgmt_oht_callback', array('absolute' => TRUE)), $options);
  dsm($response, 'Response');
}